export const NEW_COUPON_REQUEST = "NEW_COUPON_REQUEST";
export const NEW_COUPON_SUCCESS = "NEW_COUPON_SUCCESS";
export const NEW_COUPON_FAIL = "NEW_COUPON_FAIL";
export const NEW_COUPON_RESET = "NEW_COUPON_RESET";
export const ALL_COUPON_REQUEST = "ALL_COUPON_REQUEST";
export const ALL_COUPON_SUCCESS = "ALL_COUPON_SUCCESS";
export const ALL_COUPON_FAIL = "ALL_COUPON_FAIL";
export const ALL_COUPON_RESET = "ALL_COUPON_RESET";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
